name: check

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}

      - name: Check
        env:
          DOCKER_BUILDKIT: 1
        run: |
          TEMP=$(mktemp -d) && \
          git clone -q git://git.netfilter.org/iptables "${TEMP}" && \
          IPTABLES_VERSION="$(git -C "${TEMP}" tag | sort -Vr | grep -E "^v[0-9]+\.[0-9]+\.[0-9]+$" | head -n 1 | tr -d v)" && \
          sed -i -E "s/IPTABLES_VERSION: .+$/IPTABLES_VERSION: ${IPTABLES_VERSION}/" .github/workflows/release.yml

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated version bump
