name: build-static

on:
  push:
    branches:
      - main
  pull_request:

env:
  IPTABLES_VERSION: 1.8.7

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        centos:
        - 7
        - 8
        arch:
        - amd64
        - arm64
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build . \
              --file Dockerfile.centos${{ matrix.centos }} \
              --platform linux/${{ matrix.arch }} \
              --build-arg IPTABLES_VERSION \
              --output type=local,dest=.

      - name: Create release asset
        run: |
          tar -cvzf iptables-centos${{ matrix.centos }}-${{ matrix.arch }}.tar.gz  -C usr/local .

      - name: Create checksum
        run: |
          sha256sum iptables-centos${{ matrix.centos }}-${{ matrix.arch }}.tar.gz >iptables-centos${{ matrix.centos }}-${{ matrix.arch }}.tar.gz.sha256

      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: iptables-centos${{ matrix.centos }}
          path: |
            iptables-centos${{ matrix.centos }}-${{ matrix.arch }}.tar.gz
            iptables-centos${{ matrix.centos }}-${{ matrix.arch }}.tar.gz.sha256
          retention-days: 2

  release:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:

      - uses: actions/download-artifact@v2

      - name: Create release
        id: create_release
        if: github.event_name != 'pull_request'
        uses: ncipollo/release-action@v1
        with:
          #token: ${{ secrets.BOT_GITHUB_TOKEN }}
          allowUpdates: true
          name: "iptables ${{ env.IPTABLES_VERSION }}"
          tag: v${{ env.IPTABLES_VERSION }}
          draft: false
          omitBody: true
          prerelease: false
          replacesArtifacts: true
          artifacts: iptables-centos?-*.tar.gz,iptables-centos?-*.tar.gz.sha256
